# Generated by Django 2.2.5 on 2019-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='None')),
                ('idade', models.CharField(max_length=50, verbose_name='Idade')),
                ('estilos_musicais', models.CharField(max_length=50, verbose_name='Estilo musicais')),
            ],
        ),
    ]
